ARG BASE_IMAGE="ghcr.io/gbraad-devenv/ubi/systemd"
ARG BASE_VERSION="9"

FROM ${BASE_IMAGE}:${BASE_VERSION}

LABEL org.opencontainers.image.source = "https://github.com/gbraad-devenv/ubi9"

RUN cd /tmp \
    && curl -fL https://code.visualstudio.com/sha/download?build=stable\&os=cli-alpine-x64 -o code-cli.tar.gz \
    && tar zxvf code-cli.tar.gz \
    && mv code /usr/bin/code \
    && rm -f code-cli.tar.gz

# systemd
COPY assets/code-serveweb@.service /etc/systemd/system/
COPY assets/code-tunnel@.service /etc/systemd/system/
