FROM ghcr.io/gbraad-devenv/ubi/base:9

USER root

RUN dnf install -y \
        https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm \
    && dnf install -y \
        powerline \
        vim-powerline \
        stow \
    && dnf clean all \
    && rm -rf /var/cache/yum

USER gbraad

RUN git clone https://github.com/gbraad/dotfiles ~/.dotfiles \
    && ~/.dotfiles/install.sh
