ARG BASE_IMAGE="ghcr.io/gbraad-devenv/ubi/dotfiles"
ARG BASE_VERSION="9"

FROM ${BASE_IMAGE}:${BASE_VERSION}

LABEL org.opencontainers.image.source = "https://github.com/gbraad-devenv/ubi9"

USER root

ENTRYPOINT ["/sbin/init"]
